### PR TITLE
Ifteda About Page + Footer

### PR DESCRIPTION
**Pull request by ifteda**
Changes:
- incorporated copy suggestions
- hyperlinked HackBeanpot in first section
- removed HBP socials from Contact Us
- added and rearranged socials in Contact Us and Footer
- include email subject line instructions
- adjusted styling for Community Partners and Contact Us on small screens

TODO:
- update email (if going w/ info@buildforblacklives.com)

screencapture-localhost-3000-about-1594311319486

### CODE REVIEW

**Review by nupur-n — APPROVED** [review]
waiting on felicia's style change to see if causes any style conflicts - otherwise LGTM

**Review by liu-caro — APPROVED** [review]

**Comment by liu-caro** [comment]
Merge conflicts need to be resolved, but other than that - good to go!

**Comment by ifteda** [comment]
Would someone mind taking a look at the Contact Us section and see if I should reword the subject line instructions?

**Comment by liu-caro** [comment]
Subject Line instructions look great for now! We can discuss more tomorrow.

**Pull request merged**
